// ============================================================================
// RPC Bridge Implementation
// ============================================================================
//
// Implements the hbnetio-compatible RPC layer for OpenADS.
//
// Copyright 2026 OpenADS Contributors
// ============================================================================

#include "rpc_bridge.h"

#include <cstring>
#include <algorithm>
#include <chrono>
#include <sstream>

namespace openads::network {

// ===========================================================================
// RpcBridge (Server-side)
// ===========================================================================

RpcBridge::RpcBridge()
    : start_time_(std::chrono::steady_clock::now()) {
    // Register built-in functions
    register_func("server_version", builtin_server_version);
    register_func("server_time",    builtin_server_time);
    register_func("server_uptime",  builtin_server_uptime);
}

RpcBridge::~RpcBridge() {
    // Close all active streams
    std::lock_guard<std::mutex> lock(mu_);
    for (auto& [id, stream] : streams_) {
        if (stream->active) {
            stream->active = false;
            if (stream->sender_thread.joinable()) {
                stream->sender_thread.join();
            }
        }
    }
    streams_.clear();
}


// -- Registration ------------------------------------------------------------

void RpcBridge::register_func(const std::string& name, RpcFunc func) {
    std::lock_guard<std::mutex> lock(mu_);
    funcs_[name] = std::move(func);
}

void RpcBridge::register_proc(const std::string& name, RpcProc proc) {
    std::lock_guard<std::mutex> lock(mu_);
    procs_[name] = std::move(proc);
}

void RpcBridge::unregister(const std::string& name) {
    std::lock_guard<std::mutex> lock(mu_);
    funcs_.erase(name);
    procs_.erase(name);
}

bool RpcBridge::func_exists(const std::string& name) const {
    std::lock_guard<std::mutex> lock(mu_);
    return funcs_.count(name) > 0 || procs_.count(name) > 0;
}


// -- RPC dispatch ------------------------------------------------------------

util::Result<std::vector<std::uint8_t>>
RpcBridge::handle_call(const std::string& func_name,
                       const std::vector<std::vector<std::uint8_t>>& params) {
    RpcFunc func;
    {
        std::lock_guard<std::mutex> lock(mu_);
        auto it = funcs_.find(func_name);
        if (it == funcs_.end()) {
            return util::Error{20, "function not found: " + func_name};
        }
        func = it->second;
    }

    return func(params);
}

util::Result<void>
RpcBridge::handle_proc(const std::string& proc_name,
                       const std::vector<std::vector<std::uint8_t>>& params) {
    RpcProc proc;
    {
        std::lock_guard<std::mutex> lock(mu_);
        auto it = procs_.find(proc_name);
        if (it == procs_.end()) {
            return util::Error{21, "procedure not found: " + proc_name};
        }
        proc = it->second;
    }

    return proc(params);
}

util::Result<void>
RpcBridge::handle_proc_w(const std::string& proc_name,
                          const std::vector<std::vector<std::uint8_t>>& params) {
    // Same as handle_proc but the caller expects a completion ack.
    // The ack is generated by the session dispatch after this returns.
    return handle_proc(proc_name, params);
}


// -- Stream management -------------------------------------------------------

std::uint32_t RpcBridge::next_stream_id() {
    return stream_seq_++;
}

util::Result<std::uint32_t>
RpcBridge::open_stream(const std::string& func_name,
                       const std::vector<std::vector<std::uint8_t>>& params,
                       StreamCallback callback) {
    std::uint32_t id = next_stream_id();

    auto info = std::make_unique<StreamInfo>();
    info->id = id;
    info->func_name = func_name;
    info->active = true;
    info->callback = std::move(callback);

    {
        std::lock_guard<std::mutex> lock(mu_);
        streams_[id] = std::move(info);
    }

    return id;
}

util::Result<void> RpcBridge::stream_send(std::uint32_t stream_id,
                                           const std::vector<std::uint8_t>& data) {
    std::lock_guard<std::mutex> lock(mu_);
    auto it = streams_.find(stream_id);
    if (it == streams_.end() || !it->second->active) {
        return util::Error{22, "stream not found or inactive"};
    }

    it->second->callback(stream_id, data);
    return util::Ok();
}

void RpcBridge::close_stream(std::uint32_t stream_id) {
    std::lock_guard<std::mutex> lock(mu_);
    auto it = streams_.find(stream_id);
    if (it != streams_.end()) {
        it->second->active = false;
        if (it->second->sender_thread.joinable()) {
            it->second->sender_thread.detach();
        }
        streams_.erase(it);
    }
}


// -- Built-in functions ------------------------------------------------------

util::Result<std::vector<std::uint8_t>>
RpcBridge::builtin_server_version(
    const std::vector<std::vector<std::uint8_t>>&) {
    const char* ver = OPENADS_VERSION_STR;
    return rpc_serial::pack_string(ver);
}

util::Result<std::vector<std::uint8_t>>
RpcBridge::builtin_server_time(
    const std::vector<std::vector<std::uint8_t>>&) {
    auto now = std::chrono::system_clock::now();
    auto epoch = now.time_since_epoch();
    auto secs = std::chrono::duration_cast<std::chrono::seconds>(epoch);
    return rpc_serial::pack_u64(static_cast<std::uint64_t>(secs.count()));
}

util::Result<std::vector<std::uint8_t>>
RpcBridge::builtin_server_uptime(
    const std::vector<std::vector<std::uint8_t>>&) {
    auto now = std::chrono::steady_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(
        now - std::chrono::steady_clock::time_point{});
    return rpc_serial::pack_u64(static_cast<std::uint64_t>(elapsed.count()));
}


// ===========================================================================
// RpcClient (Client-side)
// ===========================================================================

RpcClient::RpcClient(std::unique_ptr<ITransport> transport)
    : transport_(std::move(transport)) {}

RpcClient::~RpcClient() {
    if (transport_) {
        transport_->close();
    }
}


// -- RPC operations ----------------------------------------------------------

util::Result<std::vector<std::uint8_t>>
RpcClient::func_exec(const std::string& name,
                      const std::vector<std::vector<std::uint8_t>>& params) {
    // Build RpcCall frame:
    //   [u8 nameLen][name][packed params]
    std::vector<std::uint8_t> payload;
    std::uint8_t name_len = static_cast<std::uint8_t>(
        std::min(name.size(), static_cast<std::size_t>(255)));
    payload.push_back(name_len);
    payload.insert(payload.end(), name.begin(), name.begin() + name_len);

    auto packed_params = rpc_serial::pack_params(params);
    payload.insert(payload.end(), packed_params.begin(), packed_params.end());

    auto result = send_and_recv(
        static_cast<std::uint8_t>(RpcOpcode::Call),
        payload.data(), payload.size());

    if (!result) return result.error();
    return result;
}

util::Result<void>
RpcClient::proc_exec(const std::string& name,
                      const std::vector<std::vector<std::uint8_t>>& params) {
    std::vector<std::uint8_t> payload;
    std::uint8_t name_len = static_cast<std::uint8_t>(
        std::min(name.size(), static_cast<std::size_t>(255)));
    payload.push_back(name_len);
    payload.insert(payload.end(), name.begin(), name.begin() + name_len);

    auto packed_params = rpc_serial::pack_params(params);
    payload.insert(payload.end(), packed_params.begin(), packed_params.end());

    auto result = send_and_recv(
        static_cast<std::uint8_t>(RpcOpcode::Proc),
        payload.data(), payload.size());

    if (!result) return result.error();
    return util::Ok();
}

util::Result<void>
RpcClient::proc_exec_w(const std::string& name,
                        const std::vector<std::vector<std::uint8_t>>& params) {
    std::vector<std::uint8_t> payload;
    std::uint8_t name_len = static_cast<std::uint8_t>(
        std::min(name.size(), static_cast<std::size_t>(255)));
    payload.push_back(name_len);
    payload.insert(payload.end(), name.begin(), name.begin() + name_len);

    auto packed_params = rpc_serial::pack_params(params);
    payload.insert(payload.end(), packed_params.begin(), packed_params.end());

    auto result = send_and_recv(
        static_cast<std::uint8_t>(RpcOpcode::ProcW),
        payload.data(), payload.size());

    if (!result) return result.error();
    return util::Ok();
}

util::Result<bool>
RpcClient::proc_exists(const std::string& name) {
    auto packed = rpc_serial::pack_string(name);
    auto result = send_and_recv(
        static_cast<std::uint8_t>(RpcOpcode::ProcExists),
        packed.data(), packed.size());

    if (!result) return result.error();

    auto unpacked = rpc_serial::unpack_u32(*result);
    if (!unpacked) return unpacked.error();
    return *unpacked != 0;
}


// -- Stream operations -------------------------------------------------------

util::Result<std::uint32_t>
RpcClient::open_data_stream(const std::string& func_name,
                             const std::vector<std::vector<std::uint8_t>>& params) {
    std::vector<std::uint8_t> payload;
    std::uint8_t name_len = static_cast<std::uint8_t>(
        std::min(func_name.size(), static_cast<std::size_t>(255)));
    payload.push_back(name_len);
    payload.insert(payload.end(), func_name.begin(),
                   func_name.begin() + name_len);

    auto packed_params = rpc_serial::pack_params(params);
    payload.insert(payload.end(), packed_params.begin(), packed_params.end());

    auto result = send_and_recv(
        static_cast<std::uint8_t>(RpcOpcode::StreamOpen),
        payload.data(), payload.size());

    if (!result) return result.error();

    auto stream_id = rpc_serial::unpack_u32(*result);
    if (!stream_id) return stream_id.error();
    return *stream_id;
}

util::Result<std::uint32_t>
RpcClient::open_item_stream(const std::string& func_name,
                             const std::vector<std::vector<std::uint8_t>>& params) {
    // Same as data stream, just a different type flag
    return open_data_stream(func_name, params);
}

util::Result<std::vector<std::uint8_t>>
RpcClient::get_stream_data(std::uint32_t stream_id) {
    auto packed = rpc_serial::pack_u32(stream_id);
    auto result = send_and_recv(
        static_cast<std::uint8_t>(RpcOpcode::StreamData),
        packed.data(), packed.size());

    return result;
}

util::Result<void>
RpcClient::close_stream(std::uint32_t stream_id) {
    auto packed = rpc_serial::pack_u32(stream_id);
    auto result = send_and_recv(
        static_cast<std::uint8_t>(RpcOpcode::StreamClose),
        packed.data(), packed.size());

    if (!result) return result.error();
    return util::Ok();
}


// -- Internal ----------------------------------------------------------------

util::Result<std::vector<std::uint8_t>>
RpcClient::send_and_recv(std::uint8_t opcode, const void* data,
                          std::size_t len) {
    std::lock_guard<std::mutex> lock(mu_);

    // Build frame: [4-byte BE length][opcode][payload]
    std::uint32_t payload_len = static_cast<std::uint32_t>(1 + len);
    std::vector<std::uint8_t> frame(4 + 1 + len);

    // Big-endian length
    frame[0] = static_cast<std::uint8_t>((payload_len >> 24) & 0xFF);
    frame[1] = static_cast<std::uint8_t>((payload_len >> 16) & 0xFF);
    frame[2] = static_cast<std::uint8_t>((payload_len >> 8) & 0xFF);
    frame[3] = static_cast<std::uint8_t>(payload_len & 0xFF);

    // Opcode
    frame[4] = opcode;

    // Payload
    if (len > 0 && data) {
        std::memcpy(frame.data() + 5, data, len);
    }

    auto sent = transport_->send(frame.data(), frame.size());
    if (!sent) return sent.error();

    // Read reply header: [4-byte BE length]
    std::uint8_t hdr[4];
    std::size_t got = 0;
    while (got < 4) {
        auto n = transport_->recv(hdr + got, 4 - got);
        if (!n) return n.error();
        if (*n == 0) return util::Error{23, "connection closed"};
        got += *n;
    }

    std::uint32_t reply_len = (static_cast<std::uint32_t>(hdr[0]) << 24) |
                               (static_cast<std::uint32_t>(hdr[1]) << 16) |
                               (static_cast<std::uint32_t>(hdr[2]) << 8)  |
                               static_cast<std::uint32_t>(hdr[3]);

    if (reply_len == 0) return std::vector<std::uint8_t>();

    std::vector<std::uint8_t> reply_buf(reply_len);
    got = 0;
    while (got < reply_len) {
        auto n = transport_->recv(reply_buf.data() + got, reply_len - got);
        if (!n) return n.error();
        if (*n == 0) return util::Error{24, "connection closed during reply"};
        got += *n;
    }

    // First byte is the reply opcode — skip it, return payload
    if (reply_len <= 1) return std::vector<std::uint8_t>();

    return std::vector<std::uint8_t>(reply_buf.begin() + 1, reply_buf.end());
}


// ===========================================================================
// Serialization helpers
// ===========================================================================

namespace rpc_serial {

std::vector<std::uint8_t> pack_string(const std::string& s) {
    std::uint32_t len = static_cast<std::uint32_t>(s.size());
    std::vector<std::uint8_t> result(4 + len);
    result[0] = static_cast<std::uint8_t>(len & 0xFF);
    result[1] = static_cast<std::uint8_t>((len >> 8) & 0xFF);
    result[2] = static_cast<std::uint8_t>((len >> 16) & 0xFF);
    result[3] = static_cast<std::uint8_t>((len >> 24) & 0xFF);
    std::memcpy(result.data() + 4, s.data(), len);
    return result;
}

std::vector<std::uint8_t> pack_raw(const void* data, std::size_t len) {
    std::uint32_t len32 = static_cast<std::uint32_t>(len);
    std::vector<std::uint8_t> result(4 + len);
    result[0] = static_cast<std::uint8_t>(len32 & 0xFF);
    result[1] = static_cast<std::uint8_t>((len32 >> 8) & 0xFF);
    result[2] = static_cast<std::uint8_t>((len32 >> 16) & 0xFF);
    result[3] = static_cast<std::uint8_t>((len32 >> 24) & 0xFF);
    if (len > 0) {
        std::memcpy(result.data() + 4, data, len);
    }
    return result;
}

std::vector<std::uint8_t> pack_u32(std::uint32_t v) {
    std::vector<std::uint8_t> result(4);
    result[0] = static_cast<std::uint8_t>(v & 0xFF);
    result[1] = static_cast<std::uint8_t>((v >> 8) & 0xFF);
    result[2] = static_cast<std::uint8_t>((v >> 16) & 0xFF);
    result[3] = static_cast<std::uint8_t>((v >> 24) & 0xFF);
    return result;
}

std::vector<std::uint8_t> pack_u64(std::uint64_t v) {
    std::vector<std::uint8_t> result(8);
    for (int i = 0; i < 8; ++i) {
        result[i] = static_cast<std::uint8_t>((v >> (i * 8)) & 0xFF);
    }
    return result;
}

util::Result<std::string> unpack_string(const std::vector<std::uint8_t>& data) {
    if (data.size() < 4) {
        return util::Error{30, "string too short"};
    }
    std::uint32_t len = static_cast<std::uint32_t>(data[0]) |
                        (static_cast<std::uint32_t>(data[1]) << 8) |
                        (static_cast<std::uint32_t>(data[2]) << 16) |
                        (static_cast<std::uint32_t>(data[3]) << 24);
    if (data.size() < 4 + len) {
        return util::Error{31, "string truncated"};
    }
    return std::string(data.begin() + 4, data.begin() + 4 + len);
}

util::Result<std::vector<std::uint8_t>>
unpack_raw(const std::vector<std::uint8_t>& data) {
    if (data.size() < 4) {
        return util::Error{32, "raw data too short"};
    }
    std::uint32_t len = static_cast<std::uint32_t>(data[0]) |
                        (static_cast<std::uint32_t>(data[1]) << 8) |
                        (static_cast<std::uint32_t>(data[2]) << 16) |
                        (static_cast<std::uint32_t>(data[3]) << 24);
    if (data.size() < 4 + len) {
        return util::Error{33, "raw data truncated"};
    }
    return std::vector<std::uint8_t>(data.begin() + 4, data.begin() + 4 + len);
}

util::Result<std::uint32_t> unpack_u32(const std::vector<std::uint8_t>& data) {
    if (data.size() < 4) {
        return util::Error{34, "u32 too short"};
    }
    return static_cast<std::uint32_t>(data[0]) |
           (static_cast<std::uint32_t>(data[1]) << 8) |
           (static_cast<std::uint32_t>(data[2]) << 16) |
           (static_cast<std::uint32_t>(data[3]) << 24);
}

util::Result<std::uint64_t> unpack_u64(const std::vector<std::uint8_t>& data) {
    if (data.size() < 8) {
        return util::Error{35, "u64 too short"};
    }
    std::uint64_t v = 0;
    for (int i = 0; i < 8; ++i) {
        v |= static_cast<std::uint64_t>(data[i]) << (i * 8);
    }
    return v;
}

std::vector<std::uint8_t>
pack_params(const std::vector<std::vector<std::uint8_t>>& params) {
    // Pack: [u16 count][param1_len][param1_data][param2_len][param2_data]...
    std::vector<std::uint8_t> result;
    std::uint16_t count = static_cast<std::uint16_t>(params.size());
    result.push_back(static_cast<std::uint8_t>(count & 0xFF));
    result.push_back(static_cast<std::uint8_t>((count >> 8) & 0xFF));

    for (const auto& param : params) {
        std::uint32_t len = static_cast<std::uint32_t>(param.size());
        result.push_back(static_cast<std::uint8_t>(len & 0xFF));
        result.push_back(static_cast<std::uint8_t>((len >> 8) & 0xFF));
        result.push_back(static_cast<std::uint8_t>((len >> 16) & 0xFF));
        result.push_back(static_cast<std::uint8_t>((len >> 24) & 0xFF));
        result.insert(result.end(), param.begin(), param.end());
    }

    return result;
}

util::Result<std::vector<std::vector<std::uint8_t>>>
unpack_params(const std::vector<std::uint8_t>& data) {
    if (data.size() < 2) {
        return util::Error{36, "params too short"};
    }

    std::uint16_t count = static_cast<std::uint16_t>(data[0]) |
                          (static_cast<std::uint16_t>(data[1]) << 8);

    std::vector<std::vector<std::uint8_t>> params;
    std::size_t off = 2;

    for (std::uint16_t i = 0; i < count; ++i) {
        if (off + 4 > data.size()) {
            return util::Error{37, "param length truncated"};
        }
        std::uint32_t len = static_cast<std::uint32_t>(data[off]) |
                            (static_cast<std::uint32_t>(data[off + 1]) << 8) |
                            (static_cast<std::uint32_t>(data[off + 2]) << 16) |
                            (static_cast<std::uint32_t>(data[off + 3]) << 24);
        off += 4;

        if (off + len > data.size()) {
            return util::Error{38, "param data truncated"};
        }
        params.emplace_back(data.begin() + off, data.begin() + off + len);
        off += len;
    }

    return params;
}

} // namespace rpc_serial

} // namespace openads::network
